# Generated by Django 3.2.6 on 2021-08-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Post name')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog_posts/')),
                ('published', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('in_archive', models.NullBooleanField(default=False)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.blogcategory', verbose_name='Category name')),
            ],
        ),
    ]
